<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configuration\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="FinAssistAI.Core">
      <HintPath>..\FinAssistAI.Core\bin\Debug\net8.0\FinAssistAI.Core.dll</HintPath>
    </Reference>
    <Reference Include="FinAssistAI.Infrastructure">
      <HintPath>..\FinAssistAI.Infrastructure\bin\Debug\net8.0\FinAssistAI.Infrastructure.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
